var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/login/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0xbn.dq._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0gsjr7_._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_04stq49.js")
R.c("server/chunks/ssr/[root-of-the-server]__013xz02._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0ppctuh._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0k1u2ck._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/_next-internal_server_app_login_page_actions_02kefem.js")
R.m(51203)
module.exports=R.m(51203).exports
