var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/student/dashboard/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__08uij4p._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0gsjr7_._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_134renu.js")
R.c("server/chunks/ssr/[root-of-the-server]__013xz02._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0ppctuh._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0k1u2ck._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/_next-internal_server_app_student_dashboard_page_actions_0t_7zjq.js")
R.m(1467)
module.exports=R.m(1467).exports
