// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/about" | "/admin" | "/admin/emails" | "/admin/resources" | "/admin/students" | "/admin/tutors" | "/admin/users" | "/become-tutor" | "/book/[tutorId]" | "/contact" | "/faq" | "/how-it-works" | "/login" | "/messages" | "/parent/dashboard" | "/pricing" | "/privacy" | "/signup" | "/signup/parent" | "/signup/student" | "/signup/tutor" | "/store" | "/store/[id]" | "/student/dashboard" | "/student/resources" | "/subjects" | "/terms" | "/tutor/dashboard" | "/tutor/dashboard/messages" | "/tutor/resources" | "/tutor/resources/upload" | "/tutors" | "/tutors/[id]"
type PageRoutes = never
type LayoutRoutes = "/" | "/admin"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes


interface ParamMap {
  "/": {}
  "/about": {}
  "/admin": {}
  "/admin/emails": {}
  "/admin/resources": {}
  "/admin/students": {}
  "/admin/tutors": {}
  "/admin/users": {}
  "/become-tutor": {}
  "/book/[tutorId]": { "tutorId": string; }
  "/contact": {}
  "/faq": {}
  "/how-it-works": {}
  "/login": {}
  "/messages": {}
  "/parent/dashboard": {}
  "/pricing": {}
  "/privacy": {}
  "/signup": {}
  "/signup/parent": {}
  "/signup/student": {}
  "/signup/tutor": {}
  "/store": {}
  "/store/[id]": { "id": string; }
  "/student/dashboard": {}
  "/student/resources": {}
  "/subjects": {}
  "/terms": {}
  "/tutor/dashboard": {}
  "/tutor/dashboard/messages": {}
  "/tutor/resources": {}
  "/tutor/resources/upload": {}
  "/tutors": {}
  "/tutors/[id]": { "id": string; }
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/admin": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }
}
