var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/store/[id]/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0~r_jnv._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0gsjr7_._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0gjp9-w.js")
R.c("server/chunks/ssr/[root-of-the-server]__013xz02._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0ppctuh._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0k1u2ck._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/_next-internal_server_app_store_[id]_page_actions_0s-ug5u.js")
R.m(91968)
module.exports=R.m(91968).exports
